#ifndef _ERRORS_H_INCLUDED
#define _ERRORS_H_INCLUDED



#define ERR_NOCLOSINGQUOTE	100
#define ERR_INVALIDCHAR		101
#define ERR_EXPECTFILENAME	102
#define ERR_COULDNTOPEN		103
#define ERR_TOOMANYFILES	104
#define ERR_UNEXPECTEDEOF	105
#define ERR_EXPECTPARAMS	106

#define ERR_EXPECTVARIABLE	200
#define ERR_EXPECTNUMBER	201

#endif
