#ifndef _ETC_H_INCLUDED
#define _ETC_H_INCLUDED

#include "codes.h"
#include "type.h"

#define NUMTRIGGERS 10

COMMAND_TABLE triggerLookup[NUMTRIGGERS] =
{
	{	"ENEMYONTILE",		TR_ENEMYONTILE,		{ PARAM_INT, PARAM_INT, 0 } },
	{	"FROGONTILE",		TR_FROGONTILE,		{ PARAM_INT, PARAM_INT, 0} },
	{	"FROGONPLATFORM",	TR_FROGONPLATFORM,	{ PARAM_INT, PARAM_INT, 0 } },
	{	"PLATFORMNEARPOINT",TR_PLATNEARPOINT,	{ PARAM_INT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, 0 } },
	{	"ENEMYNEARPOINT",	TR_ENEMYNEARPOINT,	{ PARAM_INT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, 0 } },
	{	"FROGNEARPOINT",	TR_FROGNEARPOINT,	{ PARAM_INT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, 0 } },
	{	"FROGNEARPLATFORM",	TR_FROGNEARPLAT,	{ PARAM_INT, PARAM_INT, PARAM_FLOAT, 0 } },
	{	"FROGNEARENEMY",	TR_FROGNEARENEMY,	{ PARAM_INT, PARAM_INT, PARAM_FLOAT, 0 } },
	{	"ENEMYATFLAG",		TR_ENEMYATFLAG,		{ PARAM_INT, PARAM_INT, 0 } },
	{	"PLATFORMATFLAG",	TR_PLATATFLAG,		{ PARAM_INT, PARAM_INT, 0 } },
};

#define NUMEVENTS 9

COMMAND_TABLE eventLookup[NUMEVENTS] =
{
	{	"ON",					EV_ON,					{ PARAM_TRIGGER, PARAM_BLOCK, 0 }, },
	{	"DEBUG",				EV_DEBUG,				{ PARAM_STRING, 0 } },
	{	"SCALEACTOR",			EV_CHANGEACTORSCALE,	{ PARAM_INT, PARAM_FLOAT, 0 } },
	{	"TOGGLEPLATFORMMOVE",	EV_TOGGLEPLATFORMMOVE,	{ PARAM_INT, 0 } },
	{	"TOGGLEENEMYMOVE",		EV_TOGGLEENEMYMOVE,		{ PARAM_INT, 0 } },
	{	"TOGGLETILELINK",		EV_TOGGLETILELINK,		{ PARAM_INT, 0 } },
	{	"PLAYSFX",				EV_PLAYSFX,				{ PARAM_INT, PARAM_INT, PARAM_INT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, PARAM_FLOAT, 0 } },
	{	"CHANGELEVEL",			EV_CHANGELEVEL,			{ PARAM_INT, PARAM_INT, 0 } },
	{	"ANIMATE",				EV_ANIMATEACTOR,		{ PARAM_INT, PARAM_INT, PARAM_INT, PARAM_FLOAT, 0 } },
};

#define NUMCOMMANDS 3

enum COMMANDTYPES
{
	C_IF = 0xF0,
	C_AND,
	C_OR,
	NOSUCHCOMMAND = 0xFF
};

COMMAND_TABLE commandLookup[4] =
{
	{	"IF",	C_IF, { 0 } },
	{	"AND",	C_AND, { 0 } },
	{	"OR",	C_OR, { 0 } }
};

	
const char* PARAMNAMESTRING[] = { NULL, "integer", "float", "string", "trigger", "block" };


/* ------------------------- Interpreter stuff ----------------------------- */



/* --------------------------- Compiler stuff ----------------------------- */



#endif