/*

	This file is part of Frogger2, (c) 1999 Interactive Studios Ltd.


	File		: language.c
	Programmer	: James Healey
	Date		: 31/03/99

----------------------------------------------------------------------------------------------- */

#define F3DEX_GBI_2

#include "ultra64.h"
#include "language.h"

char *DIKStrings[256][LANG_NUMLANGS] = 
{
//english			//french			//german		//italian		//american

	"",				"",               	"",             "",             "",                   
	"Escape",		"Escape",			"Escape",		"Escape",		"Escape",		// 0
	"1",			"1",              	"1",            "1",            "1",                  
	"2",			"2",              	"2",            "2",            "2",                  
	"3",			"3",              	"3",            "3",            "3",                  
	"4",			"4",              	"4",            "4",            "4",                  
	"5",			"5",              	"5",            "5",            "5",                  
	"6",			"6",              	"6",            "6",            "6",                  
	"7",			"7",              	"7",            "7",            "7",                  
	"8",			"8",              	"8",            "8",            "8",                  
	"9",			"9",              	"9",            "9",            "9",                  
	"0",			"0",				"0",			"0",			"0",			// 10 DIK_UP
	"-",			")",              	"ß",            "´",            "-",                  
	"=",			"=",              	"´",            "Ì",            "=",                  
	"Backspace",	"Backspace",      	"Backspace",    "Backspace",    "Backspace",          
	"Tab",			"Tab",            	"Tab",          "Tab",          "Tab",                
	"q",			"a",              	"q",            "q",            "q",                  
	"w",			"z",              	"w",            "w",            "w",                  
	"e",			"e",              	"e",            "e",            "e",                  
	"r",			"r",              	"r",            "r",            "r",                  
	"t",			"t",              	"t",            "t",            "t",                  
	"y",			"y",				"z",			"y",			"y",			// 20
	"u",			"u",              	"u",            "u",            "u",                  
	"i",			"i",              	"i",            "i",            "i",                  
	"o",			"o",              	"o",            "o",            "o",                  
	"p",			"p",              	"p",            "p",            "p",                  
	"[",			"^",              	"û",            "è",            "[",                  
	"]",			"$",              	"+",            "+",            "]",                  
	"Return",		"Retour",         	"Return",       "Return",       "Return",             
	"Left Control",	"Left Control",   	"Left Control", "Left Control", "Left Control",       
	"a",			"q",              	"a",            "a",            "a",                  
	"s",			"s",				"s",			"s",			"s",			// 30
	"d",			"d",              	"d",            "d",            "d",                  
	"f",			"f",              	"f",            "f",            "f",                  
	"g",			"g",              	"g",            "g",            "g",                  
	"h",			"h",              	"h",            "h",            "h",                  
	"j",			"j",              	"j",            "j",            "j",                  
	"k",			"k",              	"k",            "k",            "k",                  
	"l",			"l",              	"l",            "l",            "l",                  
	";",			"m",              	"ö",            "ò",            ";",                  
	"'",			"'",              	"'",            "'",            "'",                  
	"Grave",		"Grave",          	"Grave",        "Grave",        "Grave",              
	"Left Shift",	"Left Shift",     	"Left Shift",   "Left Shift",   "Left Shift",         
	"#",			"*",		      	"#",		    "ù",		    "Backslash",          
	"z",			"w",              	"y",            "z",            "z",                  
	"x",			"x",              	"x",            "x",            "x",                  
	"c",			"c",              	"c",            "c",            "c",                  
	"v",			"v",              	"v",            "v",            "v",                  
	"b",			"b",              	"b",            "b",            "b",                  
	"n",			"n",              	"n",            "n",            "n",                  
	"m",			",",              	"m",            "m",            "m",                  
	",",			";",				",",			",",			",",			// 50
	".",			":",              	".",            ".",            ".",                  
	"/",			"!",              	"-",            "-",            "/",                  
	"Right Shift",	"Right Shift",    	"Right Shift",  "Right Shift",  "Right Shift",        
	"*",			"*",              	"*",            "*",            "*",                  
	"Left Alt",		"Left Alt",       	"Left Alt",     "Left Alt",     "Left Alt",           
	"Space",		"Space",          	"Space",        "Space",        "Space",              
	"Caps Lock",	"Caps Lock",      	"Caps Lock",    "Caps Lock",    "Caps Lock",          
	"F1",			"F1",             	"F1",           "F1",           "F1",                 
	"F2",			"F2",             	"F2",           "F2",           "F2",                 
	"F3",			"F3",             	"F3",           "F3",           "F3",                 
	"F4",			"F4",             	"F4",           "F4",           "F4",                 
	"F5",			"F5",             	"F5",           "F5",           "F5",                 
	"F6",			"F6",             	"F6",           "F6",           "F6",                 
	"F7",			"F7",             	"F7",           "F7",           "F7",                 
	"F8",			"F8",             	"F8",           "F8",           "F8",                 
	"F9",			"F9",             	"F9",           "F9",           "F9",                 
	"F10",			"F10",            	"F10",          "F10",          "F10",                
	"NumLock",		"NumLock",        	"NumLock",      "NumLock",      "NumLock",            
	"Scroll Lock",	"Scroll Lock",    	"Scroll Lock",  "Scroll Lock",  "Scroll Lock",        
	"Numpad 7",		"Numpad 7",       	"Numpad 7",     "Numpad 7",     "Numpad 7",           
	"Numpad 8",		"Numpad 8",       	"Numpad 8",     "Numpad 8",     "Numpad 8",           
	"Numpad 9",		"Numpad 9",       	"Numpad 9",     "Numpad 9",     "Numpad 9",           
	"-",			"-",              	"-",            "-",            "-",                  
	"Numpad 4",		"Numpad 4",       	"Numpad 4",     "Numpad 4",     "Numpad 4",           
	"Numpad 5",		"Numpad 5",       	"Numpad 5",     "Numpad 5",     "Numpad 5",           
	"Numpad 6",		"Numpad 6",       	"Numpad 6",     "Numpad 6",     "Numpad 6",           
	"+",			"+",              	"+",            "+",            "+",                  
	"Numpad 1",		"Numpad 1",       	"Numpad 1",     "Numpad 1",     "Numpad 1",           
	"Numpad 2",		"Numpad 2",       	"Numpad 2",     "Numpad 2",     "Numpad 2",           
	"Numpad 3",		"Numpad 3",       	"Numpad 3",     "Numpad 3",     "Numpad 3",           
	"Numpad 0",		"Numpad 0",       	"Numpad 0",     "Numpad 0",     "Numpad 0",           
	".",			".",              	".",            ".",            ".",                  
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"\",			"<",               	"<",            "<",             "",                   
	"F11",			"F11",            	"F11",          "F11",          "F11",                
	"F12",			"F12",            	"F12",          "F12",          "F12",                
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"F13",			"F13",            	"F13",          "F13",          "F13",                
	"F14",			"F14",            	"F14",          "F14",          "F14",                
	"F15",			"F15",            	"F15",          "F15",          "F15",                
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"Kana",			"Kana",           	"Kana",         "Kana",         "Kana",               
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"Convert",		"Convert",        	"Convert",      "Convert",      "Convert",            
	"",				"",               	"",             "",             "",                   
	"No Convert",	"No Convert",     	"No Convert",   "No Convert",   "No Convert",         
	"",				"",               	"",             "",             "",                   
	"Yen",			"Yen",            	"Yen",          "Yen",          "Yen",                
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"=",			"=",              	"=",            "=",            "=",                  
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"Circumflex",	"Circumflex",     	"Circumflex",   "Circumflex",   "Circumflex",         
	"@",			"@",              	"@",            "@",            "@",                  
	":",			":",              	":",            ":",            ":",                  
	"Underline",	"Underline",      	"Underline",    "Underline",    "Underline",          
	"Kanji",		"Kanji",          	"Kanji",        "Kanji",        "Kanji",              
	"Stop",			"Stop",           	"Stop",         "Stop",         "Stop",               
	"AX",			"AX",             	"AX",           "AX",           "AX",                 
	"Unlabeled",	"Unlabeled",		"Unlabeled",	"Unlabeled",	"Unlabeled",	// 100
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"Numpad Enter",	"Numpad Enter",   	"Numpad Enter", "Numpad Enter", "Numpad Enter",       
	"Right Control","Right Control",  	"Right Control","Right Control","Right Control",      
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	",",			",",              	",",            ",",            ",",                  
	"",				"",               	"",             "",             "",                   
	"/",			"/",              	"/",            "/",            "/",                  
	"",				"",               	"",             "",             "",                   
	"SysRq",		"SysRq",          	"SysRq",        "SysRq",        "SysRq",              
	"Right Alt",	"Right Alt",      	"Right Alt",    "Right Alt",    "Right Alt",          
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"Home",			"Home",           	"Home",         "Home",         "Home",               
	"Up",			"Up",             	"Up",           "Up",           "Up",                 
	"Page Up",		"Page Up",        	"Page Up",      "Page Up",      "Page Up",            
	"",				"",               	"",             "",             "",                   
	"Left",			"Left",           	"Left",         "Left",         "Left",               
	"",				"",               	"",             "",             "",                   
	"Right",		"Right",          	"Right",        "Right",        "Right",              
	"",				"",               	"",             "",             "",                   
	"End",			"End",            	"End",          "End",          "End",                
	"Down",			"Down",           	"Down",         "Down",         "Down",               
	"Page Down",	"Page Down",      	"Page Down",    "Page Down",    "Page Down",          
	"Insert",		"Insert",         	"Insert",       "Insert",       "Insert",             
	"Delete",		"Delete",         	"Delete",       "Delete",       "Delete",             
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"",				"",               	"",             "",             "",                   
	"Left Win",		"Left Win",       	"Left Win",     "Left Win",     "Left Win",           
	"Right Win",	"Right Win",      	"Right Win",    "Right Win",    "Right Win",          
	"Apps",			"Apps",           	"Apps",         "Apps",         "Apps",               
};
