#ifndef _CODES_H_INCLUDED
#define _CODES_H_INCLUDED

/* codes.h automatically generated by ETC
   Created: Mon Sep 13 11:49:47 1999


*/

/* Commands */

#define EV_CHANGEVOLUME          13
#define EV_DROPGARIB             12
#define EV_MOVEPLAT              11
#define EV_MOVEENEMY             10
#define EV_TELEPORT              9
#define EV_SETPLATFORM           8
#define EV_SETENEMY              7
#define EV_ANIMATEACTOR          6
#define EV_RESETPLATFLAG         5
#define EV_SETPLATFLAG           4
#define EV_RESETENEMYFLAG        3
#define EV_SETENEMYFLAG          2
#define EV_SETTILE               1
#define EV_DEBUG                 0
#define EV_IF                    65
#define EV_ON                    64

/* Triggers */

#define TR_OR                    65
#define TR_AND                   64
#define TR_WAIT                  10
#define TR_PLATATFLAG            9
#define TR_ENEMYATFLAG           8
#define TR_FROGNEARENEMY         7
#define TR_FROGNEARPLAT          6
#define TR_FROGNEARPOINT         5
#define TR_ENEMYNEARPOINT        4
#define TR_PLATNEARPOINT         3
#define TR_FROGONPLATFORM        2
#define TR_FROGONTILE            1
#define TR_ENEMYONTILE           0
#endif
