/*

	This file is part of Frogger2, (c) 1999 Interactive Studios Ltd.


	File		: layoutvisual.h
	Programmer	: Andrew Eder
	Date		: 01/03/98

----------------------------------------------------------------------------------------------- */

#ifndef LAYOUTVISUAL_H_INCLUDED
#define LAYOUTVISUAL_H_INCLUDED


// DEFINES THE LAYOUT OF WORLDS AND LEVELS (WITHIN A WORLD)

#define LOAD_ALL_LEVELBANKS	0xFFFF

#define WORLD_NO_FLAGS		0
#define	WORLD_OPEN			( 1 << 0 )
#define WORLD_CLOSED		( 1 << 1 )
#define LEVEL_OPEN			( 1 << 2 )
#define LEVEL_CLOSED		( 1 << 3 )

#define MAX_WORLDS			9
#define MAX_LEVELS			10

//----- [ OBJECT AND TEXTURE BANKS ] -----

enum worldNames
{
	GARDEN,
	ANCIENTS,
	SPACE,
	CITY,
	SUBTERRANEAN,
	LABRATORY,
	TOYSHOP,
	HALLOWEEN,
	SUPERRETRO,
};

enum
{
	SYSTEM_TEX_BANK,		// Holds the fonts used
	
	GENERIC_TEX_BANK,		// Holds generic textures that are used through out the game

	GENERIC_GARDEN_TEX_BANK,
	LEVEL1_GARDEN_TEX_BANK,
	LEVEL2_GARDEN_TEX_BANK,
	LEVEL3_GARDEN_TEX_BANK,
	BOSSA_GARDEN_TEX_BANK,
	BOSSB_GARDEN_TEX_BANK,
	BONUS_GARDEN_TEX_BANK,
	MULTI_GARDEN_TEX_BANK,

	GENERIC_ANCIENT_TEX_BANK,
	LEVEL1_ANCIENT_TEX_BANK,
	LEVEL2_ANCIENT_TEX_BANK,
	LEVEL3_ANCIENT_TEX_BANK,
	BOSSA_ANCIENT_TEX_BANK,
	BOSSB_ANCIENT_TEX_BANK,
	BOSSC_ANCIENT_TEX_BANK,
	BOSSD_ANCIENT_TEX_BANK,
	BOSSE_ANCIENT_TEX_BANK,
	BONUS_ANCIENT_TEX_BANK,
	MULTI_ANCIENT_TEX_BANK,

	GENERIC_SPACE_TEX_BANK,
	LEVEL1_SPACE_TEX_BANK,
	LEVEL2_SPACE_TEX_BANK,
	LEVEL3_SPACE_TEX_BANK,
	BOSSA_SPACE_TEX_BANK,
	BONUS_SPACE_TEX_BANK,
	MULTI_SPACE_TEX_BANK,

	GENERIC_CITY_TEX_BANK,
	LEVEL1_CITY_TEX_BANK,
	LEVEL2_CITY_TEX_BANK,
	LEVEL3_CITY_TEX_BANK,
	BOSSA_CITY_TEX_BANK,
	BONUS_CITY_TEX_BANK,
	MULTI_CITY_TEX_BANK,

	GENERIC_SUBTERRANEAN_TEX_BANK,
	LEVEL1_SUBTERRANEAN_TEX_BANK,
	LEVEL2_SUBTERRANEAN_TEX_BANK,
	LEVEL3_SUBTERRANEAN_TEX_BANK,
	BOSSA_SUBTERRANEAN_TEX_BANK,
	BONUS_SUBTERRANEAN_TEX_BANK,
	MULTI_SUBTERRANEAN_TEX_BANK,

	GENERIC_LABORATORY_TEX_BANK,
	LEVEL1_LABORATORY_TEX_BANK,
	LEVEL2_LABORATORY_TEX_BANK,
	LEVEL3_LABORATORY_TEX_BANK,
	BOSSA_LABORATORY_TEX_BANK,
	BONUS_LABORATORY_TEX_BANK,
	MULTI_LABORATORY_TEX_BANK,

	GENERIC_TOYSHOP_TEX_BANK,
	LEVEL1_TOYSHOP_TEX_BANK,
	LEVEL2_TOYSHOP_TEX_BANK,
	LEVEL3_TOYSHOP_TEX_BANK,
	BOSSA_TOYSHOP_TEX_BANK,
	BONUS_TOYSHOP_TEX_BANK,
	MULTI_TOYSHOP_TEX_BANK,

	GENERIC_HALLOWEEN_TEX_BANK,
	LEVEL1_HALLOWEEN_TEX_BANK,
	LEVEL2_HALLOWEEN_TEX_BANK,
	LEVEL3_HALLOWEEN_TEX_BANK,
	BOSSA_HALLOWEEN_TEX_BANK,
	BONUS_HALLOWEEN_TEX_BANK,
	MULTI_HALLOWEEN_TEX_BANK,

	GENERIC_RETRO_TEX_BANK,
	LEVEL1_RETRO_TEX_BANK,
	LEVEL2_RETRO_TEX_BANK,
	LEVEL3_RETRO_TEX_BANK,
	BOSSA_RETRO_TEX_BANK,
	BONUS_RETRO_TEX_BANK,
	MULTI_RETRO_TEX_BANK,


	TITLES_TEX_BANK,
	OLDEFROG_TEX_BANK,
	FRONT_TEX_BANK,

	SNDVIEW_TEX_BANK,
};

enum
{
	SYSTEM_COL,

	GARDENMASTERA_COL,
	GARDENMASTERB_COL,
	GARDENLEV1_COL,
	GARDENLEV2_COL,
	GARDENLEV3_COL,
	GARDENBONUS_COL,
	GARDENMULTI_COL,

	ANCIENTMASTERA_COL,
	ANCIENTMASTERB_COL,
	ANCIENTMASTERC_COL,
	ANCIENTMASTERD_COL,
	ANCIENTMASTERE_COL,
	ANCIENTLEV1_COL,
	ANCIENTLEV2_COL,
	ANCIENTLEV3_COL,
	ANCIENTBONUS_COL,
	ANCIENTMULTI_COL,

	SPACEMASTER_COL,
	SPACELEV1_COL,
	SPACELEV2_COL,
	SPACELEV3_COL,
	SPACEBONUS_COL,
	SPACEMULTI_COL,

	CITYMASTER_COL,
	CITYLEV1_COL,
	CITYLEV2_COL,
	CITYLEV3_COL,
	CITYBONUS_COL,
	CITYMULTI_COL,

	SUBTERRANEANMASTER_COL,
	SUBTERRANEANLEV1_COL,
	SUBTERRANEANLEV2_COL,
	SUBTERRANEANLEV3_COL,
	SUBTERRANEANBONUS_COL,
	SUBTERRANEANMULTI_COL,

	LABORATORYMASTER_COL,
	LABORATORYLEV1_COL,
	LABORATORYLEV2_COL,
	LABORATORYLEV3_COL,
	LABORATORYBONUS_COL,
	LABORATORYMULTI_COL,

	TOYSHOPMASTER_COL,
	TOYSHOPLEV1_COL,
	TOYSHOPLEV2_COL,
	TOYSHOPLEV3_COL,
	TOYSHOPBONUS_COL,
	TOYSHOPMULTI_COL,

	HALLOWEENMASTER_COL,
	HALLOWEENLEV1_COL,
	HALLOWEENLEV2_COL,
	HALLOWEENLEV3_COL,
	HALLOWEENBONUS_COL,
	HALLOWEENMULTI_COL,

	RETROMASTER_COL,
	RETROLEV1_COL,
	RETROLEV2_COL,
	RETROLEV3_COL,
	RETROBONUS_COL,
	RETROMULTI_COL,
};

enum
{
	GENERIC_GARDEN_OBJ_BANK,
	LEVEL1_GARDEN_OBJ_BANK,
	LEVEL2_GARDEN_OBJ_BANK,
	LEVEL3_GARDEN_OBJ_BANK,
	BOSSA_GARDEN_OBJ_BANK,
	BOSSB_GARDEN_OBJ_BANK,
	BONUS_GARDEN_OBJ_BANK,
	MULTI_GARDEN_OBJ_BANK,
	
	GENERIC_ANCIENT_OBJ_BANK,
	LEVEL1_ANCIENT_OBJ_BANK,
	LEVEL2_ANCIENT_OBJ_BANK,
	LEVEL3_ANCIENT_OBJ_BANK,
	BOSSA_ANCIENT_OBJ_BANK,
	BOSSB_ANCIENT_OBJ_BANK,
	BOSSC_ANCIENT_OBJ_BANK,
	BOSSD_ANCIENT_OBJ_BANK,
	BOSSE_ANCIENT_OBJ_BANK,
	BONUS_ANCIENT_OBJ_BANK,
	MULTI_ANCIENT_OBJ_BANK,
		
	GENERIC_SPACE_OBJ_BANK,
	LEVEL1_SPACE_OBJ_BANK,
	LEVEL2_SPACE_OBJ_BANK,
	LEVEL3_SPACE_OBJ_BANK,
	BOSSA_SPACE_OBJ_BANK,
	BONUS_SPACE_OBJ_BANK,
	MULTI_SPACE_OBJ_BANK,
		
	GENERIC_CITY_OBJ_BANK,
	LEVEL1_CITY_OBJ_BANK,
	LEVEL2_CITY_OBJ_BANK,
	LEVEL3_CITY_OBJ_BANK,
	BOSSA_CITY_OBJ_BANK,
	BONUS_CITY_OBJ_BANK,
	MULTI_CITY_OBJ_BANK,


	GENERIC_SUBTERRANEAN_OBJ_BANK,
	LEVEL1_SUBTERRANEAN_OBJ_BANK,
	LEVEL2_SUBTERRANEAN_OBJ_BANK,
	LEVEL3_SUBTERRANEAN_OBJ_BANK,
	BOSSA_SUBTERRANEAN_OBJ_BANK,
	BONUS_SUBTERRANEAN_OBJ_BANK,
	MULTI_SUBTERRANEAN_OBJ_BANK,

	GENERIC_LABORATORY_OBJ_BANK,
	LEVEL1_LABORATORY_OBJ_BANK,
	LEVEL2_LABORATORY_OBJ_BANK,
	LEVEL3_LABORATORY_OBJ_BANK,
	BOSSA_LABORATORY_OBJ_BANK,
	BONUS_LABORATORY_OBJ_BANK,
	MULTI_LABORATORY_OBJ_BANK,

	GENERIC_TOYSHOP_OBJ_BANK,
	LEVEL1_TOYSHOP_OBJ_BANK,
	LEVEL2_TOYSHOP_OBJ_BANK,
	LEVEL3_TOYSHOP_OBJ_BANK,
	BOSSA_TOYSHOP_OBJ_BANK,
	BONUS_TOYSHOP_OBJ_BANK,
	MULTI_TOYSHOP_OBJ_BANK,

	GENERIC_HALLOWEEN_OBJ_BANK,
	LEVEL1_HALLOWEEN_OBJ_BANK,
	LEVEL2_HALLOWEEN_OBJ_BANK,
	LEVEL3_HALLOWEEN_OBJ_BANK,
	BOSSA_HALLOWEEN_OBJ_BANK,
	BONUS_HALLOWEEN_OBJ_BANK,
	MULTI_HALLOWEEN_OBJ_BANK,

	GENERIC_RETRO_OBJ_BANK,
	LEVEL1_RETRO_OBJ_BANK,
	LEVEL2_RETRO_OBJ_BANK,
	LEVEL3_RETRO_OBJ_BANK,
	BOSSA_RETRO_OBJ_BANK,
	BONUS_RETRO_OBJ_BANK,
	MULTI_RETRO_OBJ_BANK,

};


//----- [ WORLD ID's ] -----
enum
{
	WORLDID_GARDEN,
	WORLDID_ANCIENT,
	WORLDID_SPACE,
	WORLDID_CITY,
	WORLDID_SUBTERRANEAN,
	WORLDID_LABORATORY,
	WORLDID_TOYSHOP,
	WORLDID_HALLOWEEN,
	WORLDID_SUPERRETRO,
};

//----- [ LEVEL ID's ] -----
enum
{
	LEVELID_GARDENLAWN,
	LEVELID_GARDENMAZE,
	LEVELID_GARDENVEGPATCH,
	LEVELID_GARDENTREETOPSA,
	LEVELID_GARDENTREETOPSB,
	LEVELID_GARDENLOGROLL,
	LEVELID_GARDEN6,
};

enum
{
	LEVELID_ANCIENTRUINEDCITY,
	LEVELID_ANCIENTVOTG,
	LEVELID_ANCIENTMOVEIT,
	LEVELID_ANCIENTTOWEROTRAPS,
	LEVELID_ANCIENTTRAPROOM1,
	LEVELID_ANCIENTTRAPROOM2,
	LEVELID_ANCIENTTRAPROOM3,
	LEVELID_ANCIENTTRAPROOM4,
	LEVELID_ANCIENT5,
	LEVELID_ANCIENT6,
};

enum
{
	LEVELID_SPACE1,
	LEVELID_SPACE2,
	LEVELID_SPACE3,
	LEVELID_SPACE4,
	LEVELID_SPACE5,
	LEVELID_SPACE6,
};

enum
{
	LEVELID_CITYDOCKS,
	LEVELID_CITYWAREHOUSE,
	LEVELID_CITYSTREETS,
	LEVELID_CITYTOWER,
	LEVELID_CITYBONUS,
	LEVELID_CITYMULTI,
};


enum
{
	LEVELID_SUBTERRANEAN1,
	LEVELID_SUBTERRANEAN2,
	LEVELID_SUBTERRANEAN3,
	LEVELID_SUBTERRANEAN4,
	LEVELID_SUBTERRANEAN5,
	LEVELID_SUBTERRANEAN6,
};


enum
{
	LEVELID_LABORATORY1,
	LEVELID_LABORATORY2,
	LEVELID_LABORATORY3,
	LEVELID_LABORATORY4,
	LEVELID_LABORATORY5,
	LEVELID_LABORATORY6,
};

enum
{
	LEVELID_TOYSHOP1,
	LEVELID_TOYSHOP2,
	LEVELID_TOYSHOP3,
	LEVELID_TOYSHOP4,
	LEVELID_TOYSHOP5,
	LEVELID_TOYSHOP6,
};

enum
{
	LEVELID_HALLOWEEN1,
	LEVELID_HALLOWEEN2,
	LEVELID_HALLOWEEN3,
	LEVELID_HALLOWEEN4,
	LEVELID_HALLOWEEN5,
	LEVELID_HALLOWEEN6,
};

enum
{
	LEVELID_SUPERRETRO1,
	LEVELID_SUPERRETRO2,
	LEVELID_SUPERRETRO3,
	LEVELID_SUPERRETRO4,
	LEVELID_SUPERRETRO5,
	LEVELID_SUPERRETRO6,
};


enum
{
	GARDENLEV1_ENT,
	GARDENLEV2_ENT,
	GARDENLEV3_ENT,
	GARDENLEV4_ENT,
	GARDENLEV5_ENT,
	GARDENLEV6_ENT,
};

//----- [ DATA STRUCTURES ] -----

typedef struct TAGLEVEL_VISUAL_DATA
{
	unsigned char		description[32];
	unsigned long		levelID;

	long				objectBankToUse;
	long				textureBankToUse;
	long				collBank;
	long				entityDat;

	unsigned long		levelOpen;
	unsigned long		worldOpened;
	unsigned long		whole;

} LEVEL_VISUAL_DATA;


typedef struct TAGWORLD_VISUAL_DATA
{
	unsigned char		description[32];
	unsigned long		worldID;

	unsigned long		masterObjectBank;
	unsigned long		masterTextureBank;

	unsigned long		worldOpen;
	unsigned long		numLevels;
	LEVEL_VISUAL_DATA	levelVisualData[MAX_LEVELS];

} WORLD_VISUAL_DATA;


extern unsigned long worldNum;
extern unsigned long levelNum;

extern WORLD_VISUAL_DATA	worldVisualData[MAX_WORLDS];

extern UBYTE darkenedLevel;
extern short lightIntensity;


//----- [ FUNCTION PROTOTYPES ] -----

extern void LoadVisualBanksForWorld(unsigned long worldID,unsigned long levelID);

extern void FreeAllTextureBanks();
extern void FreeAllObjectBanks();

extern void InitLevel ( unsigned long worldID, unsigned long levelID );
extern void FreeLevel();

extern void FreeAllLists();

#endif
