#------------------------------------------------------------------------------
# Frogger2
#------------------------------------------------------------------------------

PROJECT = Frogger2

PROJECT_SRC	= \
	common\actor2.c\
	common\anim.c\
	common\babyfrog.c\
	common\bbtimer.c\
	common\block.c\
	common\cam.c\
	common\collect.c\
	common\crc32.c\
	common\DefData.c\
	common\enemies.c\
	common\evenfunc.c\
	common\event.c\
	common\fixed.c\
	common\flatpack.c\
	common\frogger.c\
	common\frogmove.c\
	common\frontend.c\
	common\game.c\
	common\general.c\
	common\hud.c\
	common\layout.c\
	common\levplay.c\
	common\map.c\
	common\maths.c\
	common\memload.c\
	common\menus.c\
	common\multi.c\
	common\newpsx.c\
	common\options.c\
	common\overlays.c\
	common\particle.c\
	common\path.c\
	common\platform.c\
	common\ptexture.c\
	common\savegame.c\
	common\script.c\
	common\sndview.c\
	common\specfx.c\
	common\sprite.c\
	common\story.c\
	common\textover.c\
	common\tongue.c\
	common\training.c\
	common\types.c\
	psx\audio.c\
	psx\backup.c\
	psx\bbpsiani.c\
	psx\bff_load.c\
	psx\CR_lang.c\
	psx\islfile.c\
	psx\Eff_Draw.c\
	psx\fadeout.c\
	psx\islcard.c\
	psx\islfont.c\
	psx\islpad.c\
	psx\isllocal.c\
	psx\islutil.c\
	psx\isltex.c\
	psx\map_draw.c\
	psx\memcard.c\
	psx\islvideo.c\
	psx\islxa.c\
	psx\LoadingBar.c\
	psx\objects.c\
	psx\psi.c\
	psx\temp_psx.c\
	psx\psiactor.c\
	psx\psxsprite.c\
	psx\psxtongue.c\
	psx\quatern.c\
	psx\textures.c\
	psx\World_Eff.c\
	psx\Usr.c\
	psx\water.c\
	psx\world.c\
	dc\am_audio.c\
	dc\backdrop.c\
	dc\bpacsetup.c\
	dc\bpamsetup.c\
	dc\bpamsfx.c\
	dc\bpamstream.c\
	dc\bpprintf.c\
	dc\dc_timer.c\
	dc\DCK_Maths.c\
	dc\DCK_System.c\
	dc\DCK_Texture.c\
	dc\gte.c\
	dc\main.c\
	dc\sbinit.c\

SYSTEM_INCLUDE = 

PROJECT_INCLUDE = \
		include\
		common\
		dc\
		psx\

SYSTEM_LIBS	= \
		sofdec\
		cri_adxs\
		sg_mwk2a\
		audio64\

OPTIMIZE = 0

#COMPILER =	SHC
GFXLIB = KAMUI2
OUTPUT = ELF

DEBUG  = TRUE
LIST   = FALSE

include $(KATANA_ROOT)\Sample\dc.inc
