// --------------------------------------------------------------------------------------------------------
//	GENERIC.h
//
// This header file was auto-generated by the Sega mkbank utility.
// Do not modify this file by hand.
//
// Rev:	5/4/2000 3:00 pm - File Generated
// --------------------------------------------------------------------------------------------------------

#ifndef	_GENERIC_H
#define	_GENERIC_H


#define		GENERIC_FILENAME		"GENERIC.kat"
#define		GENERIC_BANK_DATA_SIZE		1108336
#define		GENERIC_BANK_HEADER_SIZE		1236
#define		GENERIC_FROGANNOYED_WAV			0
#define		GENERIC_BABYCRY_WAV			1
#define		GENERIC_BABYHAPPY_WAV			2
#define		GENERIC_BABYHOP_WAV			3
#define		GENERIC_BABYREPLY_WAV			4
#define		GENERIC_BABYSAD_WAV			5
#define		GENERIC_DOUBLEHOP_WAV			6
#define		GENERIC_BABY_FROG_WAV			7
#define		GENERIC_FROGBELCH1_WAV			8
#define		GENERIC_FROGBELCH2_WAV			9
#define		GENERIC_FROGCROAK_WAV			10
#define		GENERIC_FROGCRUSH_WAV			11
#define		GENERIC_FROGDEATH_WAV			12
#define		GENERIC_FROGDROWN1_WAV			13
#define		GENERIC_FROGDROWN2_WAV			14
#define		GENERIC_FROGEXPLODE_WAV			15
#define		GENERIC_FROGFALL_WAV			16
#define		GENERIC_FROGMOWED_WAV			17
#define		GENERIC_FROGOKAY_WAV			18
#define		GENERIC_FROGSLIDE_WAV			19
#define		GENERIC_FROGSLIDE2_WAV			20
#define		GENERIC_GETBABYFROG_WAV			21
#define		GENERIC_GETBABYFROG1_WAV			22
#define		GENERIC_HOP2_WAV			23
#define		GENERIC_HOPONGRASS_WAV			24
#define		GENERIC_PICKUPCOIN_WAV			25
#define		GENERIC_SWITCH_WAV			26
#define		GENERIC_TONGUE_WAV			27


#endif	//	end of _GENERIC_H
