/* Saved by Nintendo 64 Sound Tools Version 2.15 of May  1 1998 */

/* Sound Effect Defines For SOUNDFX.SNG */

extern char *libmus_sfx_list[];
extern int libmus_priority_list[];

#define FX_NULL                 0
#define FX_SHIRLEYSWIM__FINS    1
#define FX_SHIRLEY_LAND         2
#define FX_SHIRLEY_LAUNCH       3
#define FX_MALLET_WALK_LEFT     4
#define FX_MALLET_WALK_RIGHT    5
#define FX_MALLET_STAMPEDE      6
#define FX_MALLET_WAIT          7
#define FX_GERERALWU_WALK_LEFT  8
#define FX_GERERALWU_WALK_RIGHT 9
#define FX_GENERALWU_DIVESNAP   10
#define FX_GENERALWU_HITGROUND  11
#define FX_SELWYNJOFF_ATTACK    12
#define FX_SELWYNJOFF_LAND      13
#define FX_SELWYNJOFF_FLAP_L    14
#define FX_SELWYNJOFF_FLAP_R    15
#define FX_SELWYNCANCER_ATTACK  16
#define FX_SELWYNKIRK_FLY       17
#define FX_DENNIS_WALK          18
#define FX_DENNIS_LAUNCH        19
#define FX_DENNIS_LAND          20
#define FX_CHUCK_CALL           21
#define FX_CHUCK_ATTACK         22
#define FX_CHUCK_JUGGLE         23
#define FX_CHUCK_WALK           24
#define FX_BUGLE_CALL           25
#define FX_BUGLE_ATTACK         26
#define FX_BUGLE_DEATH          27
#define FX_KLOSET_CALL          28
#define FX_KLOSET_WALK_LEFT     29
#define FX_KLOSET_WALK_RIGHT    30
#define FX_KLOSET_ATTACK        31
#define FX_KLOSET_SPINFLOOR     32
#define FX_KLOSET_BOXINGGLOVE   33
#define FX_KLOSET_BOMB          34
#define FX_CRUMPET_FLY          35
#define FX_CRUMPET_ATTACK       36
#define FX_CRUMPET_CALL         37
#define FX_TRACY_DANCING        38
#define FX_TRACY_CALL           39
#define FX_TRACY_WALK_LEFT      40
#define FX_TRACY_WALK_RIGHT     41
#define FX_TRACY_LAND           42
#define FX_TRACY_CHARGE         43
#define FX_TREX_CALL            44
#define FX_TREX_ATTACK          45
#define FX_TREX_FOOTSTEP_LEFT   46
#define FX_TREX_FOOTSTEP_RIGHT  47
#define FX_FLANNEL_WINGFLAP     48
#define FX_FLANNEL_CALL         49
#define FX_THRICE_ATTACK        50
#define FX_THRICE_IDLE          51
#define FX_MIKE_WALK_LEFT       52
#define FX_MIKE_WALK_RIGHT      53
#define FX_MIKE_ATTACK          54
#define FX_FUMBLE_CALL          55
#define FX_FUMBLE_WALK          56
#define FX_ETHEL_CALL           57
#define FX_ETHEL_WIND           58
#define FX_ETHEL_ATTACK         59
#define FX_FRANKIE_ATTACK_LOOPED 60
#define FX_FRANKIE_ATTACK       61
#define FX_FRANKIE_ATTACK2      62
#define FX_FRANKIE_GENERALHUM   63
#define FX_FRANKIE_WALK_LEFT    64
#define FX_FRANKIE_WALK_RIGHT   65
#define FX_FRANKIE_CALL         66
#define FX_FRANKIE_DEATH        67
#define FX_REGGIE_WALK          68
#define FX_REGGIE_DEATH         69
#define FX_SWISH_WALK_LEFT      70
#define FX_SWISH_WALK_RIGHT     71
#define FX_SWISH_ATTACK         72
#define FX_KEG_CALL             73
#define FX_KEG_WALK             74
#define FX_CHESTER_ATTACK       75
#define FX_CHESTER_WALK         76
#define FX_CHESTER_CALL         77
#define FX_SPANK_CALL_1         78
#define FX_SPANK_CALL_2         79
#define FX_SPANK_SWING          80
#define FX_SPANK_ATTACK         81
#define FX_SPANK_DROP           82
#define FX_YOOFOW_FLY           83
#define FX_YOOFOW_ATTACK        84
#define FX_OPEC_IDLE            85
#define FX_OPEC_ATTACK_LOOP     86
#define FX_OPEC_ATTACK_SINGLE   87
#define FX_CYMON_GENERAL        88
#define FX_CYMON_WALK_LEFT      89
#define FX_CYMON_WALK_RIGHT     90
#define FX_SUCKER_ATTACK_LOOP   91
#define FX_SUCKER_ATTACK        92
#define FX_SUCKER_SPIT          93
#define FX_SUCKER_CALL_1        94
#define FX_SUCKER_CALL_2        95
#define FX_SUCKER_CALL_3        96
#define FX_SUCKER_CRYSTAL       97
#define FX_ROBOT_WALK           98
#define FX_ROBOT_ATTACK         99
#define FX_ROBOT_GENERAL        100
#define FX_BOVVA_GENERAL        101
#define FX_BOVVA_ATTACK         102
#define FX_CANNONBALL_WALK      103
#define FX_SAMTEX_WALK          104
#define FX_SAMTEX_FUSE          105
#define FX_SAMTEX_EXPLODE       106
#define FX_CHICKEN_CLUCKNORMAL  107
#define FX_CHICKEN_CLUCKHALFMAD 108
#define FX_CHICKEN_CLUCKMAD     109
#define FX_CHICKEN_FART         110
#define FX_CHICKEN_BELCH        111
#define FX_SCUTTLE_GENERIC_1    112
#define FX_SCUTTLE_GENERIC_2    113
#define FX_SCUTTLE_GENERIC_3    114
#define FX_SPANK_CALL_3         115
#define FX_SPANK_CALL_4         116
#define FX_SPANK_OOF            117
#define FX_CHESTER_GROWL        118
#define FX_ROBOT_GENERAL_2      119
#define FX_ROBOT_GENERAL_3      120
#define FX_ROBOT_GENERAL_4      121
#define FX_ROBOT_GENERAL_5      122
#define FX_GENERALWU_PULLUP     123
#define FX_CHUCK_JUGGLE_ENDING  124
#define FX_TRACEY_JUMP          125
#define FX_TREX_PANTING_LOOP    126
#define FX_FUMBLE_SPOTBALL      127
#define FX_FUMBLE_KEEPBALANCE   128
#define FX_FUMBLE_PANTING_LOOP  129
#define FX_KLOSET_PIANOFALL     130
#define FX_BALLBOUNCE_RUBBER    131
#define FX_BALLBOUNCE_BOWLING   132
#define FX_BALLBOUNCE_POWER     133
#define FX_BALLBOUNCE_BEARING   134
#define FX_BALLBOUNCE_BEACH     135
#define FX_BALLBOUNCE_SNOW      136
#define FX_BALLBOUNCE_CRYSTAL   137
#define FX_BALLBOUNCE_CRYSTAL_SMASH 138
#define FX_BALL_BURST           139
#define FX_COLLECT_BONUS_1      140
#define FX_COLLECT_BONUS_1_ECHO 141
#define FX_COLLECT_BONUS_2      142
#define FX_COLLECT_POWERUP_1    143
#define FX_COLLECT_POWERUP_2    144
#define FX_COLLECT_POWERUP_3    145
#define FX_COLLECT_POWERUP_4    146
#define FX_COLLECT_POWERUP_5    147
#define FX_HAND_FOOTSTEP_LEFT   148
#define FX_HAND_FOOTSTEP_RIGHT  149
#define FX_HAND_SKID            150
#define FX_HAND_SKID_LOOP       151
#define FX_HAND_JUMP_SMALL      152
#define FX_HAND_JUMP_BIG        153
#define FX_HAND_LAND            154
#define FX_HAND_HURT_1          155
#define FX_HAND_HURT_2          156
#define FX_HAND_HURT_3          157
#define FX_HAND_PUSH_1          158
#define FX_HAND_PUSH_2          159
#define FX_HAND_FALL            160
#define FX_HAND_DIE_1           161
#define FX_HAND_DIE_2           162
#define FX_HAND_FINGERTAP_1     163
#define FX_HAND_FINGERTAP_2     164
#define FX_HAND_FINGERCLICK     165
#define FX_HAND_FISTSLAM        166
#define FX_HAND_THROW_1         167
#define FX_HAND_THROW_2         168
#define FX_HAND_THROW_3         169
#define FX_HAND_THROW_4_LOOP    170
#define FX_HAND_WHACKBALL       171
#define FX_HAND_BOUNCETAP_1     172
#define FX_HAND_BOUNCETAP_2     173
#define FX_CAST_SPELL_1         174
#define FX_CAST_SPELL_2         175
#define FX_CAST_SPELL_3         176
#define FX_POINT_DIRECTION_1    177
#define FX_POINT_DIRECTION_2    178
#define FX_GENERIC_BLEEP_1      179
#define FX_GENERIC_BLEEP_2      180
#define FX_GENERIC_BLEEP_3      181
#define FX_GENERIC_BLEEP_4      182
#define FX_ROLLING_SNOWBALL     183
#define FX_IMPACT_STONE_SMALL   184
#define FX_IMPACT_STONE_MEDIUM  185
#define FX_IMPACT_STONE_LARGE   186
#define FX_IMPACT_WOOD_SMALL    187
#define FX_IMPACT_WOOD_MEDIUM   188
#define FX_IMPACT_WOOD_LARGE    189
#define FX_IMPACT_METAL_SMALL   190
#define FX_IMPACT_METAL_MEDIUM  191
#define FX_IMPACT_METAL_LARGE   192
#define FX_IMPACT_SAND_SMALL    193
#define FX_IMPACT_SAND_MEDIUM   194
#define FX_IMPACT_SAND_LARGE    195
#define FX_IMPACT_SNOW_SMALL    196
#define FX_IMPACT_SNOW_MEDIUM   197
#define FX_IMPACT_SNOW_LARGE    198
#define FX_IMPACT_MUD_SMALL     199
#define FX_IMPACT_MUD_MEDIUM    200
#define FX_IMPACT_MUD_LARGE     201
#define FX_STONE_SCAPE_LARGE    202
#define FX_STONE_SCAPE_SMALL    203
#define FX_METAL_SCRAPE_LARGE   204
#define FX_METAL_SCRAPE_SMALL   205
#define FX_WOOD_SCRAPE_LARGE    206
#define FX_WOOD_SCRAPE_SMALL    207
#define FX_ICE_SCRAPE_LARGE     208
#define FX_ICE_SCRAPE_SMALL     209
#define FX_SWITCH_1             210
#define FX_SWITCH_2             211
#define FX_SWITCH_3             212
#define FX_SWITCH_4             213
#define FX_SWITCH_5             214
#define FX_SWITCH_6             215
#define FX_SWITCH_7             216
#define FX_SWITCH_8             217
#define FX_FROG_CALL            218
#define FX_TROUSERS_FALLDOWN    219
#define FX_IMPACT_WATER_SMALL   220
#define FX_IMPACT_WATER_MEDIUM  221
#define FX_IMPACT_WATER_LARGE   222
#define FX_EERIE_WIND           223
#define FX_BIRD_TWEET_1         224
#define FX_BIRD_TWEET_2         225
#define FX_BIRD_TWEET_3         226
#define FX_BIRD_TWEET_4         227
#define FX_BIRD_TWEET_5         228
#define FX_BIRD_TWEET_6         229
#define FX_WATERFALL            230
#define FX_WATERFALL_STEREO     231
#define FX_LAVA_1               232
#define FX_LAVA_2               233
#define FX_BAT_WINGFLAP         234
#define FX_BAT_CALL             235
#define FX_BAT_CALL_ECHO        236
#define FX_DRIPING_WATER        237
#define FX_FOUNTAIN_1           238
#define FX_FOUNTAIN_2           239
#define FX_FOUNTAIN_STEREO      240
#define FX_SEA_WAVES_1          241
#define FX_SEA_WAVES_2          242
#define FX_SEA_OFF_EDGE         243
#define FX_HEAVY_SWITCH         244
#define FX_BADGLOVE_LAUGH_1     245
#define FX_RAIN                 246
#define FX_RAIN_HEAVY           247
#define FX_THUNDER              248
#define FX_HAND2_JUMP1          249
#define FX_HAND2_JUMP2          250
#define FX_HAND2_JUMP3          251
#define FX_HAND2_JUMP4          252
#define FX_HAND2_RUNJUMP1       253
#define FX_HAND2_RUNJUMP2       254
#define FX_HAND2_RUNJUMP3       255
#define FX_HAND2_RUNJUMP4       256
#define FX_HAND2_PUSH1          257
#define FX_HAND2_PUSH2          258
#define FX_HAND2_PUSH3          259
#define FX_HAND2_PUSH4          260
#define FX_HAND2_HURT1          261
#define FX_HAND2_HURT2          262
#define FX_HAND2_HURT3          263
#define FX_HAND2_HURT4          264
#define FX_HAND2_SPELL1         265
#define FX_HAND2_SPELL2         266
#define FX_HAND2_SPELL3         267
#define FX_HAND2_SPELL4         268
#define FX_HAND2_VICTORY1       269
#define FX_HAND2_VICTORY2       270
#define FX_HAND2_VICTORY3       271
#define FX_HAND2_VICTORY4       272
#define FX_HAND2_DIE1           273
#define FX_HAND2_DIE2           274
#define FX_HAND2_DIE3           275
#define FX_HAND2_FALL           276
#define FX_BUBBLES_1            277
#define FX_BUBBLES_2            278
#define FX_BUBBLES_3            279
#define FX_COLLECT_BONUS_3      280
#define FX_COLLECT_BONUS_4      281
#define FX_COLLECT_BONUS_5      282
#define FX_CAST_SPELL_4         283
#define FX_CAST_SPELL_5         284
#define FX_HAND2_WOW            285
#define FX_BIGSPELL             286
#define FX_INTRO_BUBBLES        287
#define FX_INTRO_THUNDER        288
#define FX_INTRO_HANDOFF        289
#define FX_INTRO_SPLASH         290
#define FX_INTRO_HANDOUTWINDOW  291
#define FX_INTRO_FLOORBREAK     292
#define FX_INTRO_WIZARDFALL     293
#define FX_INTRO_RUMBLE         294
#define FX_INTRO_EXPLOSION      295
#define FX_INTRO_WIND           296
#define FX_INTRO_CHANGETOBALL   297
#define FX_INTRO_BALLBOUNCE     298
#define FX_INTRO_HANDHITGROUND  299
#define FX_INTRO_HANDOUCH       300
#define FX_INTRO_HANDGETUP      301
#define FX_INTRO_HANDYEAH       302
#define FX_INTRO_BADGLOVELAUGH  303
#define FX_PORTCULLIS1          304
#define FX_PORTCULLIS2          305
#define FX_WATER_LAPPING_1      306
#define FX_WATER_LAPPING_2      307
#define FX_SPLASH_SMALL1        308
#define FX_SPLASH_SMALL2        309
#define FX_SPLASH_SMALL3        310
#define FX_SPLASH_SMALL4        311
#define FX_ROTORBLADE           312
#define FX_SUCKER               313
#define FX_ROCK_SMASH_1         314
#define FX_ROCK_SMASH_2         315
#define FX_ROCK_SMASH_3         316
#define FX_TELEPORT_1           317
#define FX_TELEPORT_2           318
#define FX_ENTRO_WIND           319
#define FX_ENTRO_WHOOSH         320
#define FX_ENTRO_STONELAND      321
#define FX_ENTRO_FSTEP          322
#define FX_ENTRO_BIRD1          323
#define FX_ENTRO_BIRD2          324
#define FX_ENTRO_WHAA           325
#define FX_ENTRO_WHOA           326
#define FX_ENTRO_BGFALL         327
#define FX_ENTRO_BGLAND         328
#define FX_ENTRO_JUMP           329
#define FX_ENTRO_HANDATTACH     330
#define FX_ENTRO_BGRUN          331
#define FX_ENTRO_CASTSPELL      332
#define FX_ENTRO_SPELLHIT       333
#define FX_ENTRO_TRANSFORM      334
#define FX_ENTRO_CHANGE         335
#define FX_ENTRO_BLOW           336
#define FX_ENTRO_WIZWALK        337
#define FX_ENGINE_FAIL          338
#define FX_ENGINE_START         339
#define FX_ENGINE_RUNNING       340
#define FX_ENGINE_FAIL2         341
#define FX_JETPACK              342


/* End Of File */
